import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const metaPath = path.join(__dirname, 'playerMetadata.json');

const existingMeta = JSON.parse(fs.readFileSync(metaPath, 'utf8'));

const playerAdditions = {
  "MK Pandey": { name: "Manish Pandey", country: "India", role: "Batter", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak" },
  "DA Miller": { name: "David Miller", country: "South Africa", role: "Batter", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm offbreak" },
  "YK Pathan": { name: "Yusuf Pathan", country: "India", role: "All-Rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak" },
  "N Rana": { name: "Nitish Rana", country: "India", role: "Batter", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm offbreak" },
  "WP Saha": { name: "Wriddhiman Saha", country: "India", role: "Wicketkeeper", battingStyle: "Right-hand bat", bowlingStyle: "None", isWicketkeeper: true },
  "BB McCullum": { name: "Brendon McCullum", country: "New Zealand", role: "Wicketkeeper", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium", isWicketkeeper: true },
  "PA Patel": { name: "Parthiv Patel", country: "India", role: "Wicketkeeper", battingStyle: "Left-hand bat", bowlingStyle: "None", isWicketkeeper: true },
  "MA Agarwal": { name: "Mayank Agarwal", country: "India", role: "Batter", battingStyle: "Right-hand bat", bowlingStyle: "None" },
  "M Vijay": { name: "Murali Vijay", country: "India", role: "Batter", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak" },
  "B Sai Sudharsan": { name: "Sai Sudharsan", country: "India", role: "Batter", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm legbreak" },
  "SPD Smith": { name: "Steve Smith", country: "Australia", role: "Batter", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm legbreak" },
  "SE Marsh": { name: "Shaun Marsh", country: "Australia", role: "Batter", battingStyle: "Left-hand bat", bowlingStyle: "Left-arm orthodox" },
  "JH Kallis": { name: "Jacques Kallis", country: "South Africa", role: "All-Rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast-medium" },
  "DR Smith": { name: "Dwayne Smith", country: "West Indies", role: "All-Rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium" },
  "RA Tripathi": { name: "Rahul Tripathi", country: "India", role: "Batter", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium" },
  "D Padikkal": { name: "Devdutt Padikkal", country: "India", role: "Batter", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm offbreak" },
  "MP Stoinis": { name: "Marcus Stoinis", country: "Australia", role: "All-Rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium-fast" },
  "KS Williamson": { name: "Kane Williamson", country: "New Zealand", role: "Batter", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak" },
  "S Dube": { name: "Shivam Dube", country: "India", role: "All-Rounder", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm medium" },
  "AJ Finch": { name: "Aaron Finch", country: "Australia", role: "Batter", battingStyle: "Right-hand bat", bowlingStyle: "Left-arm orthodox" },
  "AC Gilchrist": { name: "Adam Gilchrist", country: "Australia", role: "Wicketkeeper", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm offbreak", isWicketkeeper: true },
  "JP Duminy": { name: "JP Duminy", country: "South Africa", role: "All-Rounder", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm offbreak" },
  "KH Pandya": { name: "Krunal Pandya", country: "India", role: "All-Rounder", battingStyle: "Left-hand bat", bowlingStyle: "Left-arm orthodox" },
  "MEK Hussey": { name: "Michael Hussey", country: "Australia", role: "Batter", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm medium" },
  "PP Shaw": { name: "Prithvi Shaw", country: "India", role: "Batter", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak" },
  "R Parag": { name: "Riyan Parag", country: "India", role: "All-Rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm legbreak" },
  "P Simran Singh": { name: "Prabhsimran Singh", country: "India", role: "Wicketkeeper", battingStyle: "Right-hand bat", bowlingStyle: "None", isWicketkeeper: true },
  "Prabhsimran Singh": { name: "Prabhsimran Singh", country: "India", role: "Wicketkeeper", battingStyle: "Right-hand bat", bowlingStyle: "None", isWicketkeeper: true },
  "MR Marsh": { name: "Mitchell Marsh", country: "Australia", role: "All-Rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium-fast" },
  "KK Nair": { name: "Karun Nair", country: "India", role: "Batter", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak" },
  "MK Tiwary": { name: "Manoj Tiwary", country: "India", role: "Batter", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm legbreak" },
  "KC Sangakkara": { name: "Kumar Sangakkara", country: "Sri Lanka", role: "Wicketkeeper", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm offbreak", isWicketkeeper: true },
  "VR Iyer": { name: "Venkatesh Iyer", country: "India", role: "All-Rounder", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm medium" },
  "JM Bairstow": { name: "Jonny Bairstow", country: "England", role: "Wicketkeeper", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium", isWicketkeeper: true },
  "AK Markram": { name: "Aiden Markram", country: "South Africa", role: "Batter", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak" },
  "RM Patidar": { name: "Rajat Patidar", country: "India", role: "Batter", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak" },
  "SO Hetmyer": { name: "Shimron Hetmyer", country: "West Indies", role: "Batter", battingStyle: "Left-hand bat", bowlingStyle: "None" },
  "NV Ojha": { name: "Naman Ojha", country: "India", role: "Wicketkeeper", battingStyle: "Right-hand bat", bowlingStyle: "None", isWicketkeeper: true },
  "DJ Hooda": { name: "Deepak Hooda", country: "India", role: "All-Rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak" },
  "SS Tiwary": { name: "Saurabh Tiwary", country: "India", role: "Batter", battingStyle: "Left-hand bat", bowlingStyle: "None" },
  "S Badrinath": { name: "Subramaniam Badrinath", country: "India", role: "Batter", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak" },
  "EJG Morgan": { name: "Eoin Morgan", country: "England", role: "Batter", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm medium" },
  "BJ Hodge": { name: "Brad Hodge", country: "Australia", role: "All-Rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak" },
  "RK Singh": { name: "Rinku Singh", country: "India", role: "Batter", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm offbreak" },
  "CA Lynn": { name: "Chris Lynn", country: "Australia", role: "Batter", battingStyle: "Right-hand bat", bowlingStyle: "Left-arm orthodox" },
  "DJ Hussey": { name: "David Hussey", country: "Australia", role: "All-Rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak" },
  "R Tewatia": { name: "Rahul Tewatia", country: "India", role: "All-Rounder", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm legbreak" },
  "PD Salt": { name: "Phil Salt", country: "England", role: "Wicketkeeper", battingStyle: "Right-hand bat", bowlingStyle: "None", isWicketkeeper: true },
  "V Shankar": { name: "Vijay Shankar", country: "India", role: "All-Rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium" },
  "KM Jadhav": { name: "Kedar Jadhav", country: "India", role: "All-Rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak" },
  "A Badoni": { name: "Ayush Badoni", country: "India", role: "Batter", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak" },
  "MM Ali": { name: "Moeen Ali", country: "England", role: "All-Rounder", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm offbreak" },
  "TM Dilshan": { name: "Tillakaratne Dilshan", country: "Sri Lanka", role: "All-Rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak" },
  "TH David": { name: "Tim David", country: "Australia", role: "Batter", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak" },
  "JM Sharma": { name: "Jitesh Sharma", country: "India", role: "Wicketkeeper", battingStyle: "Right-hand bat", bowlingStyle: "None", isWicketkeeper: true },
  "ML Hayden": { name: "Matthew Hayden", country: "Australia", role: "Batter", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm medium" },
  "M Vohra": { name: "Manan Vohra", country: "India", role: "Batter", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium" },
  "DP Conway": { name: "Devon Conway", country: "New Zealand", role: "Batter", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm medium" },
  "LMP Simmons": { name: "Lendl Simmons", country: "West Indies", role: "Batter", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium" },
  "LS Livingstone": { name: "Liam Livingstone", country: "England", role: "All-Rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm legbreak" },
  "C Green": { name: "Cameron Green", country: "Australia", role: "All-Rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast-medium" },
  "V Suryavanshi": { name: "Vaibhav Suryavanshi", country: "India", role: "Batter", battingStyle: "Left-hand bat", bowlingStyle: "Left-arm orthodox" },
  "KP Pietersen": { name: "Kevin Pietersen", country: "England", role: "Batter", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak" },
  "MC Henriques": { name: "Moises Henriques", country: "Australia", role: "All-Rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium-fast" },
  "T Stubbs": { name: "Tristan Stubbs", country: "South Africa", role: "Wicketkeeper", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak", isWicketkeeper: true },
  "Y Venugopal Rao": { name: "Venugopal Rao", country: "India", role: "Batter", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak" },
  "A Symonds": { name: "Andrew Symonds", country: "Australia", role: "All-Rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak" },
  "CL White": { name: "Cameron White", country: "Australia", role: "Batter", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm legbreak" },
  "BA Stokes": { name: "Ben Stokes", country: "England", role: "All-Rounder", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm fast-medium" },
  "HH Gibbs": { name: "Herschelle Gibbs", country: "South Africa", role: "Batter", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium" },
  "A Raghuvanshi": { name: "Angkrish Raghuvanshi", country: "India", role: "Batter", battingStyle: "Right-hand bat", bowlingStyle: "Left-arm orthodox" },
  "STR Binny": { name: "Stuart Binny", country: "India", role: "All-Rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium" },
  "RD Rickelton": { name: "Ryan Rickelton", country: "South Africa", role: "Wicketkeeper", battingStyle: "Left-hand bat", bowlingStyle: "None", isWicketkeeper: true },
  "MS Bisla": { name: "Manvinder Bisla", country: "India", role: "Wicketkeeper", battingStyle: "Right-hand bat", bowlingStyle: "None", isWicketkeeper: true },
  "N Wadhera": { name: "Nehal Wadhera", country: "India", role: "Batter", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm legbreak" },
  "M Shahrukh Khan": { name: "Shahrukh Khan", country: "India", role: "All-Rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak" },
  "ST Jayasuriya": { name: "Sanath Jayasuriya", country: "Sri Lanka", role: "All-Rounder", battingStyle: "Left-hand bat", bowlingStyle: "Left-arm orthodox" },
  "SN Khan": { name: "Sarfaraz Khan", country: "India", role: "Batter", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm legbreak" },
  "GC Smith": { name: "Graeme Smith", country: "South Africa", role: "Batter", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm offbreak" },
  "AD Mathews": { name: "Angelo Mathews", country: "Sri Lanka", role: "All-Rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium" },
  "AM Nayar": { name: "Abhishek Nayar", country: "India", role: "All-Rounder", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm medium" },
  "GJ Bailey": { name: "George Bailey", country: "Australia", role: "Batter", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium" },
  "E Lewis": { name: "Evin Lewis", country: "West Indies", role: "Batter", battingStyle: "Left-hand bat", bowlingStyle: "None" },
  "CH Morris": { name: "Chris Morris", country: "South Africa", role: "All-Rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast-medium" },
  "JJ Roy": { name: "Jason Roy", country: "England", role: "Batter", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium" },
  "D Brevis": { name: "Dewald Brevis", country: "South Africa", role: "Batter", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm legbreak" },

  // Bowlers
  "HV Patel": { name: "Harshal Patel", country: "India", role: "Fast Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium-fast" },
  "MM Sharma": { name: "Mohit Sharma", country: "India", role: "Fast Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium-fast" },
  "SN Thakur": { name: "Shardul Thakur", country: "India", role: "Fast Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium-fast" },
  "JD Unadkat": { name: "Jaydev Unadkat", country: "India", role: "Fast Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Left-arm medium-fast" },
  "CV Varun": { name: "Varun Chakravarthy", country: "India", role: "Spin Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm legbreak" },
  "R Vinay Kumar": { name: "Vinay Kumar", country: "India", role: "Fast Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium" },
  "DW Steyn": { name: "Dale Steyn", country: "South Africa", role: "Fast Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast" },
  "DL Chahar": { name: "Deepak Chahar", country: "India", role: "Fast Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium-fast" },
  "I Sharma": { name: "Ishant Sharma", country: "India", role: "Fast Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast-medium" },
  "KK Ahmed": { name: "Khaleel Ahmed", country: "India", role: "Fast Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Left-arm fast-medium" },
  "M Prasidh Krishna": { name: "Prasidh Krishna", country: "India", role: "Fast Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast" },
  "RP Singh": { name: "RP Singh", country: "India", role: "Fast Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Left-arm fast-medium" },
  "P Kumar": { name: "Praveen Kumar", country: "India", role: "Fast Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium" },
  "PP Ojha": { name: "Pragyan Ojha", country: "India", role: "Spin Bowler", battingStyle: "Left-hand bat", bowlingStyle: "Left-arm orthodox" },
  "DS Kulkarni": { name: "Dhawal Kulkarni", country: "India", role: "Fast Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium-fast" },
  "JA Morkel": { name: "Albie Morkel", country: "South Africa", role: "All-Rounder", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm medium-fast" },
  "JC Archer": { name: "Jofra Archer", country: "England", role: "Fast Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast" },
  "KV Sharma": { name: "Karn Sharma", country: "India", role: "Spin Bowler", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm legbreak" },
  "IK Pathan": { name: "Irfan Pathan", country: "India", role: "All-Rounder", battingStyle: "Left-hand bat", bowlingStyle: "Left-arm medium-fast" },
  "M Morkel": { name: "Morne Morkel", country: "South Africa", role: "Fast Bowler", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm fast" },
  "L Balaji": { name: "Lakshmipathy Balaji", country: "India", role: "Fast Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium-fast" },
  "RD Chahar": { name: "Rahul Chahar", country: "India", role: "Spin Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm legbreak" },
  "MM Patel": { name: "Munaf Patel", country: "India", role: "Fast Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium-fast" },
  "T Natarajan": { name: "T Natarajan", country: "India", role: "Fast Bowler", battingStyle: "Left-hand bat", bowlingStyle: "Left-arm medium-fast" },
  "JR Hazlewood": { name: "Josh Hazlewood", country: "Australia", role: "Fast Bowler", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm fast-medium" },
  "MJ McClenaghan": { name: "Mitchell McClenaghan", country: "New Zealand", role: "Fast Bowler", battingStyle: "Left-hand bat", bowlingStyle: "Left-arm fast-medium" },
  "R Bhatia": { name: "Rajat Bhatia", country: "India", role: "All-Rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium" },
  "JO Holder": { name: "Jason Holder", country: "West Indies", role: "All-Rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast-medium" },
  "AB Dinda": { name: "Ashok Dinda", country: "India", role: "Fast Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium-fast" },
  "SK Trivedi": { name: "Siddharth Trivedi", country: "India", role: "Fast Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium" },
  "M Muralitharan": { name: "Muttiah Muralitharan", country: "Sri Lanka", role: "Spin Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak" },
  "MG Johnson": { name: "Mitchell Johnson", country: "Australia", role: "Fast Bowler", battingStyle: "Left-hand bat", bowlingStyle: "Left-arm fast" },
  "JP Faulkner": { name: "James Faulkner", country: "Australia", role: "All-Rounder", battingStyle: "Right-hand bat", bowlingStyle: "Left-arm fast-medium" },
  "A Nortje": { name: "Anrich Nortje", country: "South Africa", role: "Fast Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast" },
  "SM Curran": { name: "Sam Curran", country: "England", role: "All-Rounder", battingStyle: "Left-hand bat", bowlingStyle: "Left-arm medium-fast" },
  "S Kaul": { name: "Siddharth Kaul", country: "India", role: "Fast Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium-fast" },
  "SK Warne": { name: "Shane Warne", country: "Australia", role: "Spin Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm legbreak" },
  "TU Deshpande": { name: "Tushar Deshpande", country: "India", role: "Fast Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium-fast" },
  "LH Ferguson": { name: "Lockie Ferguson", country: "New Zealand", role: "Fast Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast" },
  "S Gopal": { name: "Shreyas Gopal", country: "India", role: "Spin Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm legbreak" },
  "NM Coulter-Nile": { name: "Nathan Coulter-Nile", country: "Australia", role: "Fast Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast" },
  "S Nadeem": { name: "Shahbaz Nadeem", country: "India", role: "Spin Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Left-arm orthodox" },
  "TG Southee": { name: "Tim Southee", country: "New Zealand", role: "Fast Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium-fast" },
  "SB Jakati": { name: "Shadab Jakati", country: "India", role: "Spin Bowler", battingStyle: "Left-hand bat", bowlingStyle: "Left-arm orthodox" },
  "VG Arora": { name: "Vaibhav Arora", country: "India", role: "Fast Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast-medium" },
  "M Pathirana": { name: "Matheesha Pathirana", country: "Sri Lanka", role: "Fast Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast" },
  "PWH de Silva": { name: "Wanindu Hasaranga", country: "Sri Lanka", role: "Spin Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm legbreak" },
  "A Kumble": { name: "Anil Kumble", country: "India", role: "Spin Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm legbreak" },
  "RJ Harris": { name: "Ryan Harris", country: "Australia", role: "Fast Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast" },
  "M Jansen": { name: "Marco Jansen", country: "South Africa", role: "Fast Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Left-arm fast" },
  "S Aravind": { name: "Sreenath Aravind", country: "India", role: "Fast Bowler", battingStyle: "Left-hand bat", bowlingStyle: "Left-arm medium-fast" },
  "VR Aaron": { name: "Varun Aaron", country: "India", role: "Fast Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast" },
  "AJ Tye": { name: "Andrew Tye", country: "Australia", role: "Fast Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium-fast" },
  "L Ngidi": { name: "Lungi Ngidi", country: "South Africa", role: "Fast Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast" },
  "UT Yadav": { name: "Umesh Yadav", country: "India", role: "Fast Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast" },
  "Umesh Yadav": { name: "Umesh Yadav", country: "India", role: "Fast Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast" },
  "Harbhajan Singh": { name: "Harbhajan Singh", country: "India", role: "Spin Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak" },
  "Piyush Chawla": { name: "Piyush Chawla", country: "India", role: "Spin Bowler", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm legbreak" },
  "Yuzvendra Chahal": { name: "Yuzvendra Chahal", country: "India", role: "Spin Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm legbreak" },
  "YS Chahal": { name: "Yuzvendra Chahal", country: "India", role: "Spin Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm legbreak" },
  "B Kumar": { name: "Bhuvneshwar Kumar", country: "India", role: "Fast Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium-fast" },
  "Bhuvneshwar Kumar": { name: "Bhuvneshwar Kumar", country: "India", role: "Fast Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium-fast" },
  "R Ashwin": { name: "Ravichandran Ashwin", country: "India", role: "Spin Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak" },
  "SP Narine": { name: "Sunil Narine", country: "West Indies", role: "All-Rounder", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm offbreak" },
  "DJ Bravo": { name: "Dwayne Bravo", country: "West Indies", role: "All-Rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium-fast" },
  "A Mishra": { name: "Amit Mishra", country: "India", role: "Spin Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm legbreak" },
  "Harshit Rana": { name: "Harshit Rana", country: "India", role: "Fast Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast" },
  "Mayank Yadav": { name: "Mayank Yadav", country: "India", role: "Fast Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast" },
  "Abhishek Sharma": { name: "Abhishek Sharma", country: "India", role: "All-Rounder", battingStyle: "Left-hand bat", bowlingStyle: "Left-arm orthodox" },
  "Nitish Kumar Reddy": { name: "Nitish Kumar Reddy", country: "India", role: "All-Rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium-fast" }
};

const merged = { ...existingMeta, ...playerAdditions };
fs.writeFileSync(metaPath, JSON.stringify(merged, null, 2), 'utf8');
console.log(`Enriched playerMetadata.json. Total entries: ${Object.keys(merged).length}`);
